RF_03.003.01 testDeleteProjectViaDropdown POM refactoring
RedRoverSchool/JenkinsQA_2024_spring pull request #1493
Opened 2024-05-16 18:39 UTC by Pavel-Mi

https://trello.com/c/ambH4gC8/977-rf0300301-multi-configuration-project-delete-via-dropdown-pom

2024-05-16 18:49 UTC, kas-113 approved these changes

2024-05-16 19:30 UTC, KuperWoman submitted a review, later dismissed

2024-05-16 19:50 UTC, KuperWoman requested changes
здесь нарушена логика перехода по страницам 
если хотите использовать clickBreadcrumbsDropdownArrow и clickBreadcrumbsDeleteButton, их следует перенести в BasePage или MultiConfigurationProjectPage

2024-05-16 22:18 UTC, MalkoSV commented on src/test/java/school/redrover/MultiConfigurationProjectTest.java
> +                .getWelcomeJenkinsHeader();
Странная задумка и логика у этого метода getWelcomeJenkinsHeader();
Он ищет на странице элемент с конкретным текстом 'Welcome to Jenkins', а потом достает из него этот текст.

Я ищу тебя надпись 'Welcome to Jenkins'! А что у тебя написано?

Думаю, что локатор правильнее не к тексту привязывать.

2024-05-18 07:29 UTC, Pavel-Mi commented
> здесь нарушена логика перехода по страницам если хотите использовать clickBreadcrumbsDropdownArrow и clickBreadcrumbsDeleteButton, их следует перенести в BasePage или MultiConfigurationProjectPage

Внес изменения, замечания поправил

2024-05-18 07:31 UTC, Pavel-Mi commented on src/test/java/school/redrover/MultiConfigurationProjectTest.java
> +                .getWelcomeJenkinsHeader();
Изменил Assert на поиск в списке Itemов, думаю так будет правильнее

2024-05-18 09:24 UTC, KuperWoman approved these changes

2024-05-18 09:25 UTC, merged