test Tex BoxUse Form added
RedRoverSchool/JenkinsQA_2024_spring pull request #225
Opened 2024-03-28 21:16 UTC by Albina-star

2024-03-28 22:06 UTC, sashakolsky requested changes

2024-03-28 22:06 UTC, sashakolsky commented on src/test/java/school/redrover/GroupCarlthefogTest.java
> +        act.sendKeys(Keys.PAGE_DOWN).build().perform();
Page_Down для того чтобы submit было видно?
Лучше наверное использовать Actions::moveToElement метод, так как после одного Page_Down может и не будет видно нужного элемента.

2024-03-28 22:06 UTC, sashakolsky commented on src/test/java/school/redrover/GroupCarlthefogTest.java
> +        Assert.assertEquals("Name:" + FULL_NAME, actualResult1);
Аргументы идут сначала actual, потом expected.

https://www.javadoc.io/doc/org.testng/testng/latest/org/testng/Assert.html

2024-03-29 00:39 UTC, VictoriaLema approved these changes

2024-03-29 14:00 UTC, aqaestuser reviewed
хорошее ревью - попробуйте внести изменения и нужна ли помощь с конфликтом?

2024-03-29 19:24 UTC, Albina-star commented on src/test/java/school/redrover/GroupCarlthefogTest.java
> +        Assert.assertEquals("Name:" + FULL_NAME, actualResult1);
Внесу все изменения в тест.

2024-03-30 16:05 UTC, Albina-star commented
> хорошее ревью - попробуйте внести изменения и нужна ли помощь с конфликтом?
Скорей всего нужна помощь.

2024-03-30 17:19 UTC, closed without merging