init class for test crafters group
RedRoverSchool/JenkinsQA_2024_spring pull request #313
Opened 2024-03-30 20:53 UTC by Gr0zpu

This class for test crafters group.

Method initialization() sets default parameter for web driver. You can check thisMainPageTest() for how it works.

2024-03-30 21:36 UTC, AnzhelikaLa approved these changes

2024-03-30 22:49 UTC, IrynaKolh reviewed
замените driver на getDriver() по всему коду

2024-03-30 22:49 UTC, IrynaKolh commented on src/test/java/school/redrover/TutorialsNinjaTest.java
> +        WebDriver driver = initialization(URL);
Лишняя строка. Когда мы наследуем класс от BaseTest то доступ к драйверу через геттер getDriver()

замените driver на getDriver() по всему коду

2024-03-31 04:21 UTC, chudesya commented on src/test/java/school/redrover/TutorialsNinjaTest.java
> +    public void thisMainPageTest(){
Вам нужно исправить название теста на testThisMainPage. Сначала тест с маленькой буквы потом название.

2024-03-31 04:42 UTC, Gr0zpu commented on src/test/java/school/redrover/TutorialsNinjaTest.java
> +    public void thisMainPageTest(){
Это не имеет значения, класс BaseTest, c Test в конце.

2024-03-31 09:22 UTC, ppashchenkov commented on src/test/java/school/redrover/TutorialsNinjaTest.java
> +    public void testMainPageView(){
ставьте пробел между () и { вот так:
public void testMainPageView() {

2024-03-31 09:26 UTC, ppashchenkov requested changes
Зачем же так сложно? Зачем писать дополнительный метод вместо того, чтобы просто выполнить:  getDriver().get(URL);

2024-03-31 16:24 UTC, Gr0zpu commented
> Зачем же так сложно? Зачем писать дополнительный метод вместо того, чтобы просто выполнить: getDriver().get(URL);

Потому что, код reusable. Я могу в кажом тесте вызывать параметры инициализации теста. И если мне нужно централизовано изменить их,я поменяю их в одном месте. Это обычная практика DRY, что позволит избежать дублирование кода

2024-03-31 17:44 UTC, rbchn90v approved these changes

2024-03-31 17:48 UTC, merged