added test
RedRoverSchool/JenkinsQA_2024_spring pull request #318
Opened 2024-03-30 22:20 UTC by FiruzKholmatov

Added some test. Please approve!

2024-03-30 22:25 UTC, DaryaDubrovskaya approved these changes
Approved

2024-03-30 23:50 UTC, merged

2024-03-30 23:53 UTC, Gr0zpu requested changes

2024-03-30 23:53 UTC, Gr0zpu commented on src/test/java/school/redrover/GroupUnitedByJava8Test.java
> +    public void happyPathLogin() {
method name must contain 'Test'

2024-03-30 23:53 UTC, Gr0zpu commented on src/test/java/school/redrover/GroupUnitedByJava8Test.java
> +        String expectedResult = getDriver().getCurrentUrl();
I thins this is actual result; expected result is "https://www.saucedemo.com/inventory.html"

2024-03-31 10:17 UTC, FiruzKholmatov commented on src/test/java/school/redrover/GroupUnitedByJava8Test.java
> +    public void happyPathLogin() {
Thanks! Done!

2024-03-31 10:17 UTC, FiruzKholmatov commented on src/test/java/school/redrover/GroupUnitedByJava8Test.java
> +        String expectedResult = getDriver().getCurrentUrl();
Thanks! Done!