6 test Refactor+ 2 new
RedRoverSchool/JenkinsQA_2024_spring pull request #320
Opened 2024-03-30 22:47 UTC by ArtuomKudryashov

2024-03-30 22:49 UTC, ystaros approved these changes

2024-03-30 22:53 UTC, IrynaKolh reviewed
Когда мы наследуем класс от BaseTest то доступ к драйверу через геттер getDriver()

замените driver на getDriver() по всему коду

2024-03-30 22:56 UTC, ViktoriiaKarpus approved these changes

2024-03-30 22:57 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +public class GroupLearnForWinAK2024 extends BaseTest {
Привет. В названии класса должно быть слово Test

2024-03-30 22:58 UTC, Gr0zpu requested changes
final variable must have upper case

2024-03-30 22:58 UTC, Gr0zpu commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +    private static final String secondUrl = "https://demoqa.com/";
final variable must have upper case

2024-03-30 22:58 UTC, Gr0zpu commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        driver.quit();
`driver.quit()` already in BaseTest.class

2024-03-30 22:59 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +    private static final String login = "academic198405@gmail.com";
Лучше такие константы писать заглавными буквами (public static final String LOGIN, и т.д.)

2024-03-30 23:09 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +    public void CheckMenuElement() {
Название метода необходимо писать с маленькой буквы, а также лучше начинать со слова test

2024-03-30 23:09 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        List<String> expectedMenuItems = Arrays.asList(
Лучще перенести expectedMenuItems в начало теста (после 80 строчки)

2024-03-30 23:09 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +    public void CheckWeAreOnPracticeFormPage() {
с маленькой буквы надо, со слова test

2024-03-30 23:09 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        String expectedText ="Thanks for submitting the form";
Лучше вынести expectedText в начало теста (на 128 строчку)

2024-03-30 23:09 UTC, VictoriaLema commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        Assert.assertEquals(expectedText, thanks.getText());
в TestNG первым идет actual result, потом expected

2024-03-31 00:54 UTC, ArtuomKudryashov commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        String expectedText ="Thanks for submitting the form";
Здравствуйте, почему?

2024-03-31 00:55 UTC, ArtuomKudryashov commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +        List<String> expectedMenuItems = Arrays.asList(
Здравствуйте?  Почему?

2024-03-31 01:00 UTC, ArtuomKudryashov commented
> final variable must have upper case

Fixed

2024-03-31 01:01 UTC, ArtuomKudryashov commented
> Когда мы наследуем класс от BaseTest то доступ к драйверу через геттер getDriver()
> 
> замените driver на getDriver() по всему коду

Fixed

2024-03-31 01:03 UTC, ArtuomKudryashov commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +    private static final String secondUrl = "https://demoqa.com/";
Fixed

2024-03-31 01:08 UTC, ArtuomKudryashov commented
> Когда мы наследуем класс от BaseTest то доступ к драйверу через геттер getDriver()
> 
> замените driver на getDriver() по всему коду

Сергей покащал на лекции  чтобы везде не менять можно присвоить его значение как в коде

2024-03-31 02:10 UTC, aqaestuser approved these changes
Think is good enough for now

2024-03-31 02:12 UTC, ArtuomKudryashov commented on src/test/java/school/redrover/GroupLearnForWinAK2024.java
> +public class GroupLearnForWinAK2024 extends BaseTest {
fixed

2024-03-31 02:13 UTC, ArtuomKudryashov commented
> final variable must have upper case

fixed

2024-03-31 02:28 UTC, merged