Add new test
RedRoverSchool/JenkinsQA_2024_spring pull request #340
Opened 2024-03-31 09:34 UTC by IanaBlinova

Add new test

2024-03-31 09:50 UTC, EvgeniiTebenkov requested changes

2024-03-31 09:50 UTC, EvgeniiTebenkov commented on src/test/java/school/redrover/GroupCompanionsTest.java
> +    public void Firsttest() throws InterruptedException {
Firsttest не правильно, надо testFirst (имя класса пишется с заглавной буквы и в конце добавляется постфикс Test, это метод - у него сначала пишется префикс test со строчной буквы, затем имя с заглавной).
 throws InterruptedException - думаю это лишнее?

2024-03-31 09:50 UTC, EvgeniiTebenkov commented on src/test/java/school/redrover/GroupCompanionsTest.java
> +        buttonSearch.click();
Вот ты нашла элемент, кликнула по нему и что? Думаю не нужное действие. В предыдущем элементе мы проверяем вводятся символы в поле или нет.

2024-03-31 10:00 UTC, ppashchenkov requested changes
1. Имя теста должно начинаться со слова test... и описывать кратко что вы тестируете
2. Вы задали поиск "Привет, мир!" и на сайте написано в ответ: "К сожалению, на ваш поисковый запрос ничего не найдено." Если Вы это ожидали увидеть, то сделайте соотв Assert
3. На строке 46 переменную "button" переименуйте например так:  signupButton -  ведь по факту это вход в личный кабинет. Так будет понятнее что вы делаете

2024-03-31 10:21 UTC, IanaBlinova commented on src/test/java/school/redrover/GroupCompanionsTest.java
> +    public void Firsttest() throws InterruptedException {
из-за Thread.sleep - запрашивает throws InterruptedException

2024-03-31 10:21 UTC, IanaBlinova commented on src/test/java/school/redrover/GroupCompanionsTest.java
> +        buttonSearch.click();
поняла, спасибо

2024-03-31 17:41 UTC, EvgeniiTebenkov approved these changes

2024-04-01 16:39 UTC, eduardmko approved these changes

2024-04-01 17:00 UTC, EvgeniiTebenkov approved these changes

2024-04-01 17:19 UTC, ppashchenkov approved these changes

2024-04-02 03:20 UTC, merged