Al/adding1sttest
RedRoverSchool/JenkinsQA_2024_spring pull request #374
Opened 2024-03-31 20:42 UTC by Ana-Lara

Added my first simple test for checking the title of NYC 311 website

2024-03-31 21:20 UTC, Ana-Lara commented
Please approve my PR.

2024-03-31 23:21 UTC, KostyaNekrashevich commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +public class Nyc311GetTitleTest {
нужно наследоваться от BaseTest

2024-03-31 23:24 UTC, KostyaNekrashevich approved these changes
Т.к. это первая попытка, дам Approve. Но мы уже ушли дальше и нужно много чего переделывать в тесте. (как минимум сделать extends BaseTest)

2024-04-01 02:35 UTC, ppashchenkov requested changes
1. Пожалуйста, наследуйте свой класс от абстрактного класса BaseTest
2. Никогда не в тестах не вызывайте статический класс main в качестве названия теста!!!
3. Название теста должно начинаться со слова test и далее краткий смысл теста, например в вашем случае так:
@Test
public void testTitleNycGovPortal() {
4. Также забудьте в тестах System.Out.Print - удалите строку 17

Сделайте такие изменения и тест будет принят! =))

2024-04-01 05:10 UTC, Ana-Lara commented
> 1. Пожалуйста, наследуйте свой класс от абстрактного класса BaseTest
> 2. Никогда не в тестах не вызывайте статический класс main в качестве названия теста!!!
> 3. Название теста должно начинаться со слова test и далее краткий смысл теста, например в вашем случае так:
>    @test
>    public void testTitleNycGovPortal() {
> 4. Также забудьте в тестах System.Out.Print - удалите строку 17
> 
> Сделайте такие изменения и тест будет принят! =))

Done. Please review my changes. Thank you!

2024-04-01 19:07 UTC, KostyaNekrashevich commented
> > 1. Пожалуйста, наследуйте свой класс от абстрактного класса BaseTest
> > 2. Никогда не в тестах не вызывайте статический класс main в качестве названия теста!!!
> > 3. Название теста должно начинаться со слова test и далее краткий смысл теста, например в вашем случае так:
> >    @test
> >    public void testTitleNycGovPortal() {
> > 4. Также забудьте в тестах System.Out.Print - удалите строку 17
> > 
> > Сделайте такие изменения и тест будет принят! =))
> 
> Could you, please, approve my PR after the changes done? I wanted to merge.

Вы не сделали, всё что от вас требовалось. 
Вы почему-то наследовались от какого-то непонятного класса AqaGroupBaseTest, а нужно наследоваться просто от BaseTest (который создал Сергей, этот класс лежит в Package - runner). 
В итоге вам все еще нужно отнаследоваться от BaseTest и после этого немного переписать свой тест, уже не нужно будет делать .quit(); и использовать СhromeDriver (нужно использовать getDriver()).
Пересмотрите 2 последние лекции с Сергеем, он там подробно все объяснял.

2024-04-02 05:26 UTC, ppashchenkov commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +public class Nyc311GetTitleTest extends AqaGroupBaseTest {
Вот так правильно:
public class Nyc311GetTitleTest extends BaseTest {

2024-04-02 05:26 UTC, ppashchenkov commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +    public void testGetNYC311Title(String[] args) {
Вот так правильно:
public void testGetNYC311Title() {

2024-04-02 05:26 UTC, ppashchenkov commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +        WebDriver driver = new ChromeDriver();
Вот так правильно:
WebDriver driver = getDriver();

2024-04-02 05:26 UTC, ppashchenkov commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +        driver.quit();
Эту строку надо УДАЛИТЬ!
driver.quit();

2024-04-02 05:41 UTC, Gr0zpu approved these changes

2024-04-02 05:41 UTC, Gr0zpu commented on src/test/java/school/redrover/Nyc311GetTitleTest.java
> +    public static void main(String[] args) {
method name must contain test<TestName> not main

2024-04-02 19:52 UTC, merged