Ad/refactoring
RedRoverSchool/JenkinsQA_2024_spring pull request #377
Opened 2024-03-31 20:57 UTC by sashokdzr

2024-03-31 21:13 UTC, IrynaKolh approved these changes
refactor you code, use getDriver() instead of driver (see the last Sergey's lecture)

2024-03-31 21:13 UTC, IrynaKolh commented on src/test/java/school/redrover/JavaHashGroupTest.java
> +import org.openqa.selenium.WebDriver;
you should use getDriver() from BaseTest. Don't need to import WebDriver again

2024-04-01 03:06 UTC, ppashchenkov requested changes
1. Пожалуйста, наследуйте свой класс от класса BaseTest:
public class SofaTest extends BaseTest {
2. После наследования строка 40 станет лишней, удалите её
 WebDriver driver = getDriver();
И вместо driver используйте метод getDriver() из класса BaseTest
3. В остальном сойдёт!=))

2024-04-01 09:22 UTC, 1ROCKSTAR1 approved these changes

2024-04-01 10:50 UTC, sashokdzr commented
> refactor you code, use getDriver() instead of driver (see the last Sergey's lecture)

2024-04-01 10:52 UTC, sashokdzr commented on src/test/java/school/redrover/JavaHashGroupTest.java
> +import org.openqa.selenium.WebDriver;
> you should use getDriver() from BaseTest. Don't need to import WebDriver again

Thanks Iryna for review. I don't use imported calss as driver

**WebDriver driver = getDriver();**

2024-04-01 11:02 UTC, sashokdzr commented
@ppashchenkov пожалуйста разблокируй PR для мерджа

> 1. Пожалуйста, наследуйте свой класс от класса BaseTest:
>    public class SofaTest extends BaseTest {
> 2. После наследования строка 40 станет лишней, удалите её
>    WebDriver driver = getDriver();
>    И вместо driver используйте метод getDriver() из класса BaseTest
> 3. В остальном сойдёт!=))

Спасибо за ревью, но класс SofaTest удаляется в этом ПР. Никакие изменения в удаляемом классе не ожидаются. Пожалуйста посмотри внимательно.

2024-04-01 19:55 UTC, closed without merging