Test1
RedRoverSchool/JenkinsQA_2024_spring pull request #435
Opened 2024-04-01 20:09 UTC by MarinovMaksim

Merge SimpleTest to CrazyTestersTest

2024-04-01 21:04 UTC, ppashchenkov requested changes
Замените на 21 и на 67 строках:
WebDriver driver = new ChromeDriver();
на:
WebDriver driver = getDriver();

2024-04-02 04:18 UTC, AllaBird commented on src/test/java/school/redrover/CrazyTestersTest.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));
подождать нужно после открытия страницы и внести изменения ввиду наследования baseTest(101 убрать и везде изменить на getDriver()

2024-04-02 04:19 UTC, AllaBird commented on src/test/java/school/redrover/CrazyTestersTest.java
> +        Assert.assertEquals("Epic sadface: Password is required", message.getText());
первым идет actual result, потом expected

2024-04-04 20:57 UTC, PRoman-86 commented on src/test/java/school/redrover/CrazyTestersTest.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));
Почему, она выносит в переменную. Это не ошибка, используется геттер, лишний объект драйвера не создается.

2024-04-04 20:58 UTC, PRoman-86 commented on src/test/java/school/redrover/CrazyTestersTest.java
> +        Assert.assertEquals("Epic sadface: Password is required", message.getText());
Не обязательно, в зависимости от требований

2024-04-04 20:58 UTC, HelenMyronyuk commented on src/test/java/school/redrover/CrazyTestersTest.java
> +
драйвер не з селениума, наверное для работы з базами даных 
можно просто удалить

2024-04-04 20:59 UTC, HelenMyronyuk approved these changes

2024-04-04 21:00 UTC, PRoman-86 commented on src/test/java/school/redrover/CrazyTestersTest.java
> +
Думается, аппрувнуть можно, уберет потом.

2024-04-04 21:00 UTC, PRoman-86 approved these changes
Комментарии принять к сведению при написании тестов в последующем.

2024-04-05 03:05 UTC, closed without merging