add test loginConduit
RedRoverSchool/JenkinsQA_2024_spring pull request #436
Opened 2024-04-01 20:11 UTC by karel77

2024-04-01 20:18 UTC, AliaksandrMakaranka approved these changes

2024-04-01 20:44 UTC, sashakolsky approved these changes

2024-04-01 21:08 UTC, ppashchenkov requested changes

2024-04-01 21:08 UTC, ppashchenkov commented on src/test/java/school/redrover/GroupCarlthefogTest.java
> +        WebDriver driver = new ChromeDriver();
Ваш класс наследуется от BaseTest, поэтому замените 
WebDriver driver = new ChromeDriver();
на
WebDriver driver = getDriver();

2024-04-02 05:15 UTC, ppashchenkov approved these changes

2024-04-02 05:16 UTC, ppashchenkov reviewed
Так НЕЛЬЗЯ:
WebDriver driver = new ChromeDriver();

2024-04-02 12:58 UTC, merged