As/new test
RedRoverSchool/JenkinsQA_2024_spring pull request #440
Opened 2024-04-01 20:55 UTC by AnastasiaSerova1

Added my test to group class

2024-04-02 05:32 UTC, ppashchenkov reviewed
Плииз, уберите все комментарии из теста!!!

2024-04-02 07:24 UTC, KathyGU commented on src/test/java/school/redrover/TestWikipedia.java
> +public class TestWikipedia {
класс должен наследоваться от BaseTest, тогда не будет необходимости в методах с аннотациями  @BeforeClass and @AfterClass

2024-04-02 18:31 UTC, sashakolsky requested changes
Комментарии, лишние пустые строки,путь к драйверу на диске С - это все не нужно. 
И Thread.sleep лучше заменить на вейтер.

И да, если наследоваться от BaseTest то и драйвер там уже есть и браузер сам будет закрываться.

2024-04-02 22:47 UTC, closed without merging

2024-04-03 01:17 UTC, KostyaNekrashevich commented
Так же в тестах не должно быть System.out.println.