Yy/enter my test
RedRoverSchool/JenkinsQA_2024_spring pull request #517
Opened 2024-04-03 15:49 UTC by juliayeg

2024-04-03 15:54 UTC, tereshenkov29 requested changes
класс должен наследоваться от BaseTest (extends BaseTest)
что нужно сделать после этого
* убрать конструкцию WebDriver driver = new ChromeDriver(); - в этом теперь нет необходимости
* везде в коде заменить объект driver на вызов метода getDriver()
* в конце тестов убрать getDriver().quit(); (потому что этот метод есть в BaseTest, и он и так выполнится)

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +public class VivaTest {
класс должен наследоваться от BaseTest

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        WebDriver driver = new ChromeDriver();
когда будет наследование - не нужно будет создавать WebDriver

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));
а все обращения к объекту driver надо заменить на вызов метода getDriver()

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        driver.quit();
и quit тоже нужно будет убрать

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        WebElement submitButton = driver.findElement(By.xpath("//*[@id=\"search-box\"]/button"));//find button
экранированные кавычки лучше заменить на одинарные '

2024-04-03 15:54 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        textBox.sendKeys("ddd");
необязательно создавать переменную, можно находить элемент и сразу выполнять над ним действие

2024-04-04 03:58 UTC, juliayeg commented
Thank you very much for all your comments, I hope I addressed them. Have a great day

2024-04-04 07:37 UTC, tereshenkov29 approved these changes
я поставлю аппрув, потому что тест безобидный, ничего не ломает
но обратите внимание на комменты по коду

2024-04-04 07:37 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +    public void testTest() throws InterruptedException {
testTest() - очень "говорящее" название для теста :)

2024-04-04 07:37 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        //WebElement textBox = getDriver().findElement(By.name("search")).sendKeys("ffff");
закоментированный код лучше удалять

2024-04-04 07:37 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        getDriver().findElement(By.name("search")).clear();;
а в чем смысл этих 2-х строк кода? ввели ffff и сразу после этого очистили поле?

2024-04-04 07:37 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        WebElement submitButton = getDriver().findElement(By.linkText("Schedules and Maps"));
нашли элемент, сохранили его в переменную - но что дальше? над переменной не производится никаких действий

2024-04-04 07:37 UTC, tereshenkov29 commented on src/test/java/school/redrover/runner/VivaTest.java
> +        Assert.assertEquals(currentUrl, "https://www.yrt.ca/en/schedules-and-maps/viva-routes.aspx");
если вы хотите проверить, что открылась ожидаемая страница (не случилось никаких редиректов, URL не поменялся и всё такое), то тогда можно вставлять ассерт сразу после 20-й строки

2024-04-04 14:07 UTC, SafronovaOlga approved these changes

2024-04-04 21:10 UTC, merged