TC_00.001.34 | Item > New Item > Create Freestyle Project
RedRoverSchool/JenkinsQA_2024_spring pull request #693
Opened 2024-04-14 22:51 UTC by kubanbekoff

https://trello.com/c/iMboPETE/132-tc0000134-item-new-item-create-freestyle-project

2024-04-14 23:15 UTC, tereshenkov29 requested changes

2024-04-14 23:15 UTC, tereshenkov29 commented on src/test/java/school/redrover/ProjectCreateTest.java
> +public class ProjectCreateTest extends BaseTest {
название класса должно отражать проверяемую сущность
не очень понятно, что такое ProjectCreate

варианты FreestyleProjectTest или NewItemTest были бы лучше

2024-04-14 23:15 UTC, tereshenkov29 commented on src/test/java/school/redrover/ProjectCreateTest.java
> +    public void testCreateProject() {
testCreateProject - а какой именно project? скорее всего Freestyle - тогда надо указать в названии

2024-04-14 23:15 UTC, tereshenkov29 commented on src/test/java/school/redrover/ProjectCreateTest.java
> +                "//*[@id='side-panel']/div[1]/div[1]/span/a")).click();
какой-то длинный xpath получился - можно сделать короче (по атрибуту href)

2024-04-14 23:15 UTC, tereshenkov29 commented on src/test/java/school/redrover/ProjectCreateTest.java
> +                "Test project", Keys.ENTER);
и после выполнения 23-й строки пользователь оказывается на той же странице, что и после 19-й строки - тогда зачем код в 21-23 строках? выглядит как лишний

2024-04-15 07:23 UTC, tereshenkov29 approved these changes

2024-04-15 16:17 UTC, maksin82 approved these changes

2024-04-15 16:21 UTC, merged