TC_00.001.07 add post condition to the test, move variables from test…
RedRoverSchool/JenkinsQA_2024_spring pull request #720
Opened 2024-04-15 14:38 UTC by IrinaFrutiz

https://trello.com/c/KOPatdk7/129-tc0000107-check-name-of-a-new-freestyle-project-on-the-dashboard

2024-04-15 16:13 UTC, tereshenkov29 requested changes
Это выглядит как рефакторинг, а не как новый тест - тогда надо поправить карточку и названия

строки 24-26 - не нужно явно удалять созданную тестом сущность, если это не является проверкой по тесту

2024-04-16 18:55 UTC, NatashaOvs1 approved these changes

2024-04-16 18:55 UTC, kubanbekoff approved these changes

2024-04-16 18:55 UTC, zapletin-dk approved these changes

2024-04-16 18:55 UTC, gele4ka approved these changes

2024-04-16 19:05 UTC, merged