TC_14.002.01 | Header > Seach box > Search functionality > Verify Search result is displayed
RedRoverSchool/JenkinsQA_2024_spring pull request #723
Opened 2024-04-15 16:22 UTC by Turii

https://trello.com/c/SZoh5XWS

2024-04-15 16:34 UTC, SafronovaOlga approved these changes

2024-04-15 16:48 UTC, sashakolsky requested changes
Message коммита должен начинаться с номера Test Case из Trello.

2024-04-15 16:48 UTC, sashakolsky commented on src/test/java/school/redrover/HeaderTest.java
> +    WebDriverWait wait = new WebDriverWait(getDriver(), Duration.ofSeconds(5));
Если не используется то надо убрать.

2024-04-15 16:55 UTC, Turii commented on src/test/java/school/redrover/HeaderTest.java
> +    WebDriverWait wait = new WebDriverWait(getDriver(), Duration.ofSeconds(5));
Done
Thank you

2024-04-17 04:20 UTC, sashakolsky approved these changes

2024-04-17 15:55 UTC, merged