TC_02.005.02 | Pipeline > Edit description > Preview description
RedRoverSchool/JenkinsQA_2024_spring pull request #764
Opened 2024-04-16 16:53 UTC by Albina-star

TC - https://trello.com/c/uBH6pZeI/221-tc0200502-pipeline-edit-description-preview-description

2024-04-16 18:51 UTC, sashakolsky commented
Commit message should contain test case number from trello.

2024-04-16 19:22 UTC, Albina-star commented
> Commit message should contain test case number from trello.

ok

2024-04-16 19:41 UTC, Albina-star commented
> > Commit message should contain test case number from trello.
> 
> ok,
testAddDescriptionPreview()
TC_02.005.02 | Pipeline > Edit description > Preview description

2024-04-17 01:05 UTC, AllaBird approved these changes

2024-04-17 01:28 UTC, svcat approved these changes

2024-04-17 01:28 UTC, svcat commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        final String description = "First";
в Строке 60 вы используете заглавные буквы, а в 61 - маленькие. ЛУчше выбрать один стиль и его придерживаться. Обычно константы пишут заглавными буквами

2024-04-17 01:28 UTC, svcat commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        WebElement previewDescription = getDriver().findElement(By.xpath("//div[@class='textarea-preview']"));
Сергей говорил на лекции, что не стоит создавать переменную, если она используется один раз.
Но на мой взгляд вкусовщина. Кому как проще читать

2024-04-17 04:45 UTC, sashakolsky requested changes

2024-04-17 04:51 UTC, sashakolsky commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        WebElement previewDescription = getDriver().findElement(By.xpath("//div[@class='textarea-preview']"));
Проблема в том что любая вкусовщина решается правилами Тим Лида. В данный момент это Сережа, так что за ним последнее слово. 🙌

2024-04-17 06:44 UTC, AllaBird commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        final String description = "First";
Я думаю, если внутри теста только одного используется ,то маленькими буквами. Если ни в одном то можно вынести как константу с БОЛЬШИХ в класс из теста

2024-04-17 13:37 UTC, Albina-star commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        getDriver().findElement(By.cssSelector("#breadcrumbs > li:nth-child(3)")).click();
Made changes

2024-04-17 13:37 UTC, Albina-star commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        final String description = "First";
Хорошо

2024-04-17 13:38 UTC, Albina-star commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        WebElement previewDescription = getDriver().findElement(By.xpath("//div[@class='textarea-preview']"));
ок, переделала без переменной

2024-04-17 13:39 UTC, Albina-star commented on src/test/java/school/redrover/PipelineProjectTest.java
> +        final String description = "First";
Хорошо, учту

2024-04-19 18:37 UTC, sashakolsky approved these changes

2024-04-19 19:06 UTC, merged