TC_00.000.08 | Freestyle project>Create Freestyle Project
RedRoverSchool/JenkinsQA_2024_spring pull request #815
Opened 2024-04-17 23:01 UTC by Margusha83

https://trello.com/c/nCEXJq60/102-tc0000008-freestyle-projectcreate-freestyle-project

2024-04-17 23:13 UTC, tereshenkov29 requested changes

2024-04-17 23:13 UTC, tereshenkov29 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +public class CreateFreestyleProject2Test extends BaseTest {
название класса должно быть по названию тестируемой сущности, а не по выполняемому действию
Create - лишнее, надо поправить

2024-04-17 23:13 UTC, tereshenkov29 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        getDriver().findElement(By.xpath("//div[@id='tasks']/descendant::div[1]")).click();
xpath может быть короче и проще (ищем элемент-ссылку по атрибуту href)

2024-04-17 23:13 UTC, tereshenkov29 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        final String expectedFreestyleProjectName = "FreestyleProjectTest";
немного странное название для переменной - непонятно, почему expected

2024-04-17 23:13 UTC, tereshenkov29 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        getDriver().findElement(By.xpath("//div[@id='items']//*[text()='Freestyle project']//ancestor::li"))
и тут тоже можно проще - найти по значению атрибута class

2024-04-17 23:13 UTC, tereshenkov29 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        assertEquals(expectedNameText,expectedNameText);
текст expectedNameText сравнивается с текстом expectedNameText - результат всегда будет True 
надо поправить

2024-04-18 18:37 UTC, Margusha83 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        getDriver().findElement(By.xpath("//div[@id='tasks']/descendant::div[1]")).click();
Done

2024-04-18 19:04 UTC, Margusha83 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        getDriver().findElement(By.xpath("//div[@id='items']//*[text()='Freestyle project']//ancestor::li"))
Done

2024-04-18 19:04 UTC, Margusha83 commented on src/test/java/school/redrover/CreateFreestyleProject2Test.java
> +        assertEquals(expectedNameText,expectedNameText);
Done

2024-04-18 20:19 UTC, tereshenkov29 approved these changes

2024-04-18 20:25 UTC, IrynaKolh approved these changes

2024-04-18 20:35 UTC, merged